version: '3'
services:
  webserver:
    build:
      dockerfile: ./Dockerfile 
    restart: always
    ports:
      - 8000:80
      - 8333:443
    volumes:
      - ../web:/var/www/html
    depends_on:
      - db

  db:
    container_name: dbContainer
    image: mariadb
    volumes:
      - ./datadir:/var/lib/mysql
    restart: always
    ports:
      - 9906:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: edydb
      MYSQL_USER: edy
      MYSQL_PASSWORD: password
